// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedScheduler.Api.Data;

#nullable disable

namespace SeedScheduler.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413131545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SeedScheduler.Api.Models.Garden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("SeedScheduler.Api.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPerennial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxGerminationDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHarvestMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSowMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinGerminationDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinHarvestMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinSowMonth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantSpacing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowSpacing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SowDepth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("SeedScheduler.Api.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
