// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeedScheduler.Api.Data;

#nullable disable

namespace SeedScheduler.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629131619_GardensFrostMigration")]
    partial class GardensFrostMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("SeedScheduler.Api.Models.Garden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageFirstFrostDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageLastFrostDay")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gardens");
                });

            modelBuilder.Entity("SeedScheduler.Api.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("MaxGerminationDays")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxHarvestMonth")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxHeight")
                        .HasColumnType("REAL");

                    b.Property<float>("MaxSowMonth")
                        .HasColumnType("REAL");

                    b.Property<float>("MinGerminationDays")
                        .HasColumnType("REAL");

                    b.Property<float>("MinHarvestMonth")
                        .HasColumnType("REAL");

                    b.Property<float>("MinHeight")
                        .HasColumnType("REAL");

                    b.Property<float>("MinSowMonth")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PlantSpacing")
                        .HasColumnType("REAL");

                    b.Property<float>("RowSpacing")
                        .HasColumnType("REAL");

                    b.Property<float>("SowDepth")
                        .HasColumnType("REAL");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("SeedScheduler.Api.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
